import Head from "next/head";
import Image from "next/image";
import Header from "../Components/Header";
import styled from "styled-components";
import NavLink from "../Components/NavLink.js";
import dynamic from "next/dynamic";
import LandingBottomPart from "../Components/LandingBottomPart";
const Landing = dynamic(() => import("../Components/Landing"), {
  ssr: false,
});
export default function Home() {
  return (
    <div>
      <Head>
        <title>Der FINANZCHECK Kreditvergleich</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <header>
        <Header />
        <NavLink />
      </header>
      {/* body */}
      <main>
        <Landing />
        <LandingBottomPart />
      </main>
      {/* footer */}
    </div>
  );
}
