import Head from "next/head";
import Image from "next/image";
import Header from "../Components/Header";
import styled from "styled-components";
import NavLink from "../Components/NavLink.js";
import dynamic from "next/dynamic";
import LandingBottomPart from "../Components/LandingBottomPart";
import CarouselSection from "../Components/CarouselSection";
import TopArticles from "../Components/TopArticles";
import Trusted from "../Components/Trusted";
import MidArticles from "../Components/MidArticles";
import BottomList from "../Components/BottomList";
import Footer from "../Components/Footer";
const Landing = dynamic(() => import("../Components/Landing"), {
  ssr: false,
});
export default function Home() {
  return (
    <div>
      <Head>
        <title>Der FINANZCHECK Kreditvergleich</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <header>
        <Header />
        <NavLink />
      </header>
      {/* body */}
      <main>
        <Landing />
        <LandingBottomPart />
        <CarouselSection />
        <TopArticles />
        <Trusted />
        <MidArticles />
        <BottomList />
      </main>
      {/* footer */}
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
